moon:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: moon_order
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9sif3Xvh4rTTVZP2LY
    access-key-secret: ttP89i2qHR4QO4TEanUKehQ56RJ8w4
    bucket-name: moon-order
  redis:
    host: localhost
    port: 6379
    #    password: xxxx
    #    database: 0
  wechat:
    appid: wxc18fc1e91378fef9
    secret: c469f64c80dd4c0242adf81e4cdb9ba0
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url:
