server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${moon.datasource.driver-class-name}
      url: jdbc:mysql://${moon.datasource.host}:${moon.datasource.port}/${moon.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${moon.datasource.username}
      password: ${moon.datasource.password}
  redis:
    host: ${moon.redis.host}
    port: ${moon.redis.port}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.moon.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      moon:
        mapper: debug
        service: info
        controller: info

moon:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: moonorderadmin
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: moonorderuser
    user-ttl: 720000000
    user-token-name: authentication
  alioss:
    endpoint: ${moon.alioss.endpoint}
    access-key-id: ${moon.alioss.access-key-id}
    access-key-secret: ${moon.alioss.access-key-secret}
    bucket-name: ${moon.alioss.bucket-name}
  wechat:
    appid: ${moon.wechat.appid}
    secret: ${moon.wechat.secret}
    mchid: ${moon.wechat.mchid}
    mch-serial-no: ${moon.wechat.mch-serial-no}
    private-key-file-path: ${moon.wechat.private-key-file-path}
    api-v3-key: ${moon.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${moon.wechat.private-key-file-path}
    notify-url: ${moon.wechat.notify-url}
    refund-notify-url: ${moon.wechat.refund-notify-url}
