moon:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: moon_order
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9sif3Xvh4rTTVZP2LY
    access-key-secret: ttP89i2qHR4QO4TEanUKehQ56RJ8w4
    bucket-name: moon-order